In [3]:
import numpy as np

### Creating arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(5, 4.1)

array([4.1, 4.1, 4.1, 4.1, 4.1])

In [10]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[2]

np.int64(3)

In [12]:
a[2] = 30
a

array([ 1,  2, 30,  5,  7, 12])

In [14]:
np.arange(2, 10)


array([2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Multi-dimensional arrays

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [22]:
n[1, 1]

np.int64(5)

In [26]:
n[0]

array([ 1, 20,  3])

In [25]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[:, 1]

array([20,  5,  8])

### Randomly generated arrays

In [35]:
np.random.seed(10)
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [36]:
np.random.seed(10)
np.random.randn(5, 2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [37]:
np.random.seed(10)
np.random.randint(low=0, high=100, size=(5, 2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

### Element-wise operations

In [38]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [39]:
a + 2

array([2, 3, 4, 5, 6])

In [40]:
a * 10

array([ 0, 10, 20, 30, 40])

In [41]:
a / 5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [44]:
b = (10 + (a * 2)) ** 2 / 100

In [47]:
print(a)
print(b)
a + b


[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison operations

In [48]:
a >= 3

array([False, False, False,  True,  True])

In [49]:
print(a)
print(b)
a > b

[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([False, False,  True,  True,  True])

In [50]:
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [51]:
a.min()

np.int64(0)

In [52]:
a.max()

np.int64(4)

In [53]:
a.sum()

np.int64(10)

In [54]:
a.mean()

np.float64(2.0)

In [55]:
a.std()

np.float64(1.4142135623730951)

In [57]:
print(n)
n.sum()

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


np.int64(63)